item {
	id: 1
	name: 'speed limit 20'
	id: 2
	name: 'speed limit 30'
	id: '3'
	name: 'speed limit 50'
	id: '4'
	name: 'speed limit 60'
	id: '5'
	name: 'speed limit 70'
	id: '6'
	name: 'speed limit 80'
	id: '7'
	name: 'restriction ends 80'
	id: '8'
	name: 'no overtaking'
	id: '9'
	name: 'priority at next intersection'
	id: '10'
	name: 'priority road'
	id: '11'
	name: 'give way'
	id: '12'
	name: 'stop'
	id: '13'
	name: 'no traffic both ways'
	id: '14'
	name: 'no trucks'
	id: '15'
	name: 'no entry'
	id: '16'
	name: 'danger'
	id: '17'
	name: 'bend left'
	id: '18'
	name: 'bend right'
	id: '19'
	name: 'bend'
	id: '20'
	name: 'uneven road'
	id: '21'
	name: 'slippery road'
	id: '22'
	name: 'road narrows'
	id: '23'
	name: 'construction'
	id: '24'
	name: 'traffic signal'
	id: '25'
	name: 'pedestrian crossing'
	id: '26'
	name: 'school crossing'
	id: '27'
	name: 'cycles crossing'
	id: '28'
	name: 'snow'
	id: '29'
	name: 'animals'
	id: '30'
	name: 'restriction ends'
	id: '31'
	name: 'go right'
	id: '32'
	name: 'go left'
	id: '33'
	name: 'go straight'
	id: '34'
	name: 'go right or straight'
	id: '35'
	name: 'go left or straight'
	id: '36'
	name: 'keep right'
	id: '37'
	name: 'keep left'
	id: '38'
	name: 'round about'
	id: '39'
	name: 'speed limit 100'
	id: '40'
	name: 'speed limit 120'
}
